import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
// import Navbar from '@/components/Navbar'
import LenisProvider from '@/components/LenisProvider'
import Footer from '@/components/Footer'

const poppins = Poppins({ weight: ["200", '300', '400', '500', '600', '700', '800', '900'], subsets: ["latin-ext"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <LenisProvider>
          {children}
          <Footer/>
        </LenisProvider>
      </body>
    </html>
  )
}
